### ISSUE TITLE
请问这个将文本转化为二元标注的to_punc_data.py是不是存在问题呀

### ISSUE THREAD

**Issue by CiCistar** [WeiYi95/SBD#1]
您好，我在运行您的to_punc_data.py文件时好像并没有达到实际的效果，没有成功将文本转化为您sample中的格式，请问这个代码是存在漏洞，如果是的话，可以冒昧问您要一份您更新后的BIO标注转化代码吗？谢谢，打扰了！

**Comment by WeiYi95** [comment]
不好意思，这两天有点忙忘回了。
那个确实是有问题的，所以README里面也没写用那个转换。用于转换的脚本没有找到，所以就把这个传上来作为参考。如果急用的话，可以参考着这个改。我尽量周末补个能正确运行的~

**Comment by CiCistar** [comment]
好的好的，谢谢您！

**Comment by WeiYi95** [comment]
代码其实可以用的，只是需要特定的输入格式。我在README里加了说明，希望对你有帮助。

**Comment by CiCistar** [comment]
好的，谢谢~明白了！
