### ISSUE TITLE
关于验证的do_eval问题

### ISSUE THREAD

**Issue by CiCistar** [WeiYi95/SBD#2]
您好，为什么我试了您的这个do_eval没有办法成功，请问您的eval测试命令这样哪里需要改吗？
python BERT_SEG.py  --training_examples=16 --eval_examples=26 --pred_examples=1 --task_name="SEG" --do_train=False --do_eval=False --do_predict=True --data_dir=data --vocab_file=vocab.txt --bert_config_file=bert_config.json --init_checkpoint=output/model.ckpt-10 --max_seq_length=64 --train_batch_size=8 --learning_rate=5e-5 --num_train_epochs=5.0 --output_dir=output

**Comment by WeiYi95** [comment]
当时并没有支持do_eval这个参数。如果想在验证集上验证效果，需要先预测然后评估。代码没有对在训练过程成中在验证模型效果进行支持。
由于时间原因，短期可能不会支持。如果您改好了，欢迎提merge request😀

**Comment by CiCistar** [comment]
修改metric_fn为precision = tf_metrics.precision(label_ids, predictions, 17, ....)可以运行，具体效果还待测试
